DROP TABLE IF EXISTS LOG;
DROP TABLE IF EXISTS STUDENT;

CREATE TABLE STUDENT (
    STUDENTID   INT,
    SURNAME     NVARCHAR(50),
    GIVENNAME   NVARCHAR(50),
    MOBILE      NVARCHAR(15),
    PRIMARY KEY (STUDENTID)
);

CREATE TABLE LOG (
    LOGID       INT IDENTITY(1,1),
    STUDENTID   INT,
    DATETIMECHANGED DATETIME,
    DBUSER          NVARCHAR(20),
    OLDSURNAME      NVARCHAR(50),
    NEWSURNAME      NVARCHAR(50),
    OLDGIVENNAME    NVARCHAR(50),
    NEWGIVENNAME    NVARCHAR(50),
    OLDMOBILE       NVARCHAR(10),
    NEWMOBILE       NVARCHAR(15),
    PRIMARY KEY (LOGID),
    FOREIGN KEY (STUDENTID) REFERENCES STUDENT    
);

GO
DROP TRIGGER IF EXISTS INSERT_TRIGGER;
GO
CREATE TRIGGER INSERT_TRIGGER ON STUDENT
FOR INSERT
AS

BEGIN
    INSERT INTO LOG (STUDENTID, DATETIMECHANGED, DBUSER, OLDSURNAME, NEWSURNAME, OLDGIVENNAME, NEWGIVENNAME, OLDMOBILE, NEWMOBILE)
    SELECT  STUDENTID,
            GETDATE(),
            CURRENT_USER,
            NULL,
            SURNAME,
            NULL,
            GIVENNAME,
            NULL,
            MOBILE
    FROM INSERTED
END;

GO

INSERT INTO STUDENT (STUDENTID, SURNAME, GIVENNAME, MOBILE)
VALUES  (1, 'Zali', 'Spurgeon', '0468455972'),
        (2, 'Glasses', 'Joey', '0395629476');

SELECT * FROM STUDENT;
SELECT * FROM LOG;

GO
DROP TRIGGER IF EXISTS UPDATE_TRIGGER;
GO
CREATE TRIGGER UPDATE_TRIGGER ON STUDENT
FOR UPDATE
AS
BEGIN
    INSERT INTO LOG (STUDENTID, DATETIMECHANGED, DBUSER, OLDSURNAME, NEWSURNAME, OLDGIVENNAME, NEWGIVENNAME, OLDMOBILE, NEWMOBILE)
    SELECT  I.STUDENTID,
            GETDATE(),
            CURRENT_USER,
            D.SURNAME,
            I.SURNAME,
            D.GIVENNAME,
            I.GIVENNAME,
            D.MOBILE,
            I.MOBILE
    FROM INSERTED I
    INNER JOIN DELETED D
    ON I.STUDENTID = D.STUDENTID
END;

GO

UPDATE STUDENT
SET SURNAME = 'Bone';

SELECT * FROM LOG;
            
GO
DROP TRIGGER IF EXISTS DELETE_TRIGGER;
GO
CREATE TRIGGER DELETE_TRIGGER ON STUDENT
INSTEAD OF DELETE
AS
BEGIN
    SELECT 'Students cannot be deleted' AS [MESSAGE]
END;

GO

DELETE FROM STUDENT WHERE STUDENTID = 1;

